"""Build the upload folder for a tuned LFM2.5 checkpoint (issue 39, task t15).

A fine-tune of LFM2.5 is a Derivative Work under the LFM Open License v1.0
(docs/lfm-license-notes.md). Before anything is uploaded, even to a private
repository, the folder must carry what Section 4 of the licence asks for:

- ``LICENSE``: the base model's own licence file, byte for byte;
- ``NOTICE``: a prominent statement that the files were modified, and how,
  keeping Liquid AI's notices;
- ``README.md``: a model card whose front matter names the licence and the
  base model, stating the modification, the per-user commercial threshold,
  the data and the teacher models that generated and reviewed it (spec c45).

When ``--licence-kind=apache`` the base is assumed to carry the Apache License
2.0; the notice and card are rewritten without the LFM-specific terms and
without naming Liquid AI as the licensor.

The script copies the merged checkpoint, refuses a chat template that differs
from the base's (spec c33), writes the three files and checks them. It never
uploads: publishing is an operator action (``grant run --inject
HF_TOKEN=HF_TOKEN -- hf upload --private ...``).

    python scripts/lfm-finetune/release_bundle.py --merged runs/r7/merged \
        --base-snapshot <cache>/hub/models--LiquidAI--LFM2.5-350M/snapshots/<commit> \
        --repo jetson-ai-lab/lfm2.5-350m-nvsh-triage --run r7 \
        --results measure/r7-val.md --data-summary "945 examples: ..." --out bundle/
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent

#: The first line of the licence file LiquidAI ships with LFM2.5.
LICENSE_FIRST_LINE = "LFM Open License v1.0"

#: Phrases the model card must contain; checked after it is written.
REQUIRED_CARD_PHRASES = (
    "license_name: lfm1.0",
    "license_link: LICENSE",
    "base_model:",
    "modified",
    "10,000,000",
    "Generated by",
    "Reviewed by",
)

#: Required phrases for an Apache-2.0 model card.
APACHE_REQUIRED_CARD_PHRASES = ("license: apache-2.0",)

#: Who wrote and checked the synthetic training requests (spec c45), as the
#: operator's local gateway serves them. Their outputs are the data; their
#: licences do not carry over to it.
TEACHERS = (
    ("Qwen 3.6 35B-A3B", "Apache-2.0", "Generated by: wrote request variations"),
    ("Qwen 3.8 27B", "Apache-2.0", "Generated by: copyedited each variation"),
    ("Gemma 4 26B-A4B", "Apache-2.0", "Reviewed by: reviewer A, accepts or rejects"),
    ("Nemotron 3.5 Lightning", "OpenMDW-1.1", "Reviewed by: reviewer B, accepts or rejects"),
)


def _stage_cache():
    spec = importlib.util.spec_from_file_location("stage_cache", _HERE / "stage_cache.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def results_table(results: Path) -> str:
    """The measurement's metric table (the first markdown table in *results*)."""
    lines: list[str] = []
    for line in results.read_text(encoding="utf-8").splitlines():
        if line.startswith("|"):
            lines.append(line)
        elif lines:
            break
    if not lines:
        raise ValueError(f"{results} holds no metric table")
    return "\n".join(lines)


def notice(base_repo: str, base_revision: str, repo: str, licence_kind: str = "lfm") -> str:
    if licence_kind == "apache":
        return f"""{repo}

This model is a derivative work based on {base_repo} (revision {base_revision}),
licensed under the Apache License 2.0.

Modifications: the weights were changed by LoRA fine-tuning, then merged, to
teach the model the nvsh Tier 2 control tools (propose, explain, escalate) and
the operations in nvsh's table. The tokenizer and chat template are unchanged.
The fine-tune was made by the nvsh project (https://github.com/agentculture/nvsh).
"""
    return f"""{repo}

This model is a modified version of {base_repo} (revision {base_revision}),
made available by Liquid AI, Inc. under the LFM Open License v1.0 (see LICENSE).

Modifications: the weights were changed by LoRA fine-tuning, then merged, to
teach the model the nvsh Tier 2 control tools (propose, explain, escalate) and
the operations in nvsh's table. The tokenizer and chat template are unchanged.
The fine-tune was made by the nvsh project (https://github.com/agentculture/nvsh).

All copyright, patent, trademark and attribution notices of the original work
are retained. "LFM" and "Liquid AI" are Liquid AI's names, used here only to
describe the origin of the work.
"""


def model_card(
    *,
    repo: str,
    base_repo: str,
    base_revision: str,
    run: str,
    table: str,
    results_name: str,
    data_summary: str,
    licence_kind: str = "lfm",
    tool_call_parser: str = "lfm2",
) -> str:
    teachers = "\n".join(f"| {name} | {licence} | {role} |" for name, licence, role in TEACHERS)
    if licence_kind == "apache":
        family = base_repo.split("/")[0].lower()
        licence_front = "license: apache-2.0\n"
        base_tags = f"- {family}\n"
        derivative = "**This is a derivative work based on the base model.**"
        licence_section = (
            "This model is a derivative of the base model under the Apache License 2.0.\n"
            "The ``LICENSE`` file is included. The base model is\n"
            f"[{base_repo}](https://huggingface.co/{base_repo})\n"
            f"(revision `{base_revision}`).\n"
        )
    else:
        licence_front = "license: other\nlicense_name: lfm1.0\nlicense_link: LICENSE\n"
        base_tags = "- liquid\n- lfm2.5\n"
        derivative = "**This is a modified version of LFM2.5-350M.**"
        licence_section = (
            "LFM Open License v1.0, the base model's licence, included as `LICENSE`.\n"
            "Commercial use is licensed only to a user whose legal entity, including every\n"
            "entity under common control, has annual revenue below USD 10,000,000. **This\n"
            "threshold applies to every user of this model**, not only its publisher. A\n"
            "user above it needs their own agreement with Liquid AI.\n"
        )
    return f"""---
library_name: transformers
{licence_front}base_model: {base_repo}
pipeline_tag: text-generation
tags:
{base_tags}- nvsh
- tool-calling
---

# {repo.split("/")[-1]}

A fine-tune of [{base_repo}](https://huggingface.co/{base_repo}) (revision
`{base_revision}`) for [nvsh](https://github.com/agentculture/nvsh)'s Tier 2:
given an operator's request at a Jetson or DGX Spark shell, answer with one
of three tools: `propose` (an operation from nvsh's table, for the operator
to approve), `explain` (a short answer) or `escalate` (hand the request to a
full agent). Training run `{run}`.

{derivative} The weights were changed by
LoRA fine-tuning and merged; the tokenizer and chat template are the base
model's, unchanged. See `NOTICE`.

## Licence

{licence_section}
## Use with nvsh

```toml
[tiers]
enabled = true

[tiers.lfm]
model = "{repo}"
engine = "vllm"
tool_call_parser = "{tool_call_parser}"
```

nvsh only proposes; the operator approves every change. See nvsh's
`docs/tier2.md`.

## Results

Measured with nvsh's `scripts/lfm-finetune/measure.py` through the real Tier 2
launcher on a DGX Spark ({results_name}):

{table}

## Training data

{data_summary}

Requests were rewritten into variations by a local pipeline
(`scripts/lfm-finetune/augment.py`). A variation was kept only when both
reviewers accepted it and deterministic guards found no operation identifier
or copied answer wording in it. A training record that repeats a
validation or test entry is dropped (`merge_variations.py --exclude`), and the
test side is never used to choose a run.

| Model | Licence | Role |
|---|---|---|
{teachers}

The teachers' licences do not carry over to their outputs.

## Recipe

`scripts/lfm-finetune/pipeline.sh` and `docs/lfm-finetune.md` in the nvsh
repository: seeded split, augmentation, assistant-only-loss LoRA training,
merge, and measurement against the stock model.
"""


def build(
    *,
    merged: Path,
    base_snapshot: Path,
    repo: str,
    run: str,
    results: Path,
    data_summary: str,
    out: Path,
    licence_kind: str = "lfm",
    tool_call_parser: str = "lfm2",
) -> str:
    """Write the upload folder to *out*; return the checkpoint's revision."""
    stage_cache = _stage_cache()
    if stage_cache.chat_template(merged) != stage_cache.chat_template(base_snapshot):
        raise ValueError("the checkpoint's chat template differs from the base model's (c33)")
    licence = base_snapshot / "LICENSE"
    if not licence.is_file():
        raise ValueError(f"{base_snapshot} ships no LICENSE file")
    if licence_kind == "apache":
        text = licence.read_text(encoding="utf-8")
        non_empty = [line for line in text.splitlines() if line.strip()]
        first5 = non_empty[:5]
        if not any("Apache License" in line for line in first5):
            raise ValueError(
                f"{licence} does not appear to be the Apache License 2.0 (not Apache-2.0)"
            )
        if not any("Version 2.0" in line for line in first5):
            raise ValueError(
                f"{licence} does not appear to be the Apache License 2.0 (not Apache-2.0)"
            )
    else:
        if not licence.read_text(encoding="utf-8").lstrip().startswith(LICENSE_FIRST_LINE):
            raise ValueError(f"{licence} is not the {LICENSE_FIRST_LINE}")
    if not data_summary.strip():
        raise ValueError("--data-summary must describe the training data")
    base_repo, base_revision = _base_identity(base_snapshot)
    if out.exists():
        if any(out.iterdir()):
            raise ValueError(f"{out} is not empty")
        out.rmdir()
    shutil.copytree(merged, out)
    shutil.copyfile(licence, out / "LICENSE")
    (out / "NOTICE").write_text(
        notice(base_repo, base_revision, repo, licence_kind=licence_kind), encoding="utf-8"
    )
    card = model_card(
        repo=repo,
        base_repo=base_repo,
        base_revision=base_revision,
        run=run,
        table=results_table(results),
        results_name=results.name,
        data_summary=data_summary.strip(),
        licence_kind=licence_kind,
        tool_call_parser=tool_call_parser,
    )
    required = APACHE_REQUIRED_CARD_PHRASES if licence_kind == "apache" else REQUIRED_CARD_PHRASES
    missing = [phrase for phrase in required if phrase not in card]
    if missing:
        raise ValueError(f"model card is missing {missing}")
    (out / "README.md").write_text(card, encoding="utf-8")
    return stage_cache.revision_of(merged)


def _base_identity(base_snapshot: Path) -> tuple[str, str]:
    """``(owner/name, revision)`` from a cache path ``models--owner--name/snapshots/<rev>``."""
    revision = base_snapshot.name
    repo_folder = base_snapshot.parent.parent.name
    if base_snapshot.parent.name != "snapshots" or not repo_folder.startswith("models--"):
        raise ValueError(f"{base_snapshot} is not a Hugging Face cache snapshot")
    owner, _, name = repo_folder[len("models--") :].partition("--")
    return f"{owner}/{name}", revision


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--merged", required=True, type=Path)
    parser.add_argument("--base-snapshot", required=True, type=Path)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--run", required=True, help="training run name, e.g. r7")
    parser.add_argument("--results", required=True, type=Path, help="measure.py report")
    parser.add_argument("--data-summary", required=True)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument(
        "--licence-kind",
        choices=("lfm", "apache"),
        default="lfm",
        help="licence mode for the base model",
    )
    parser.add_argument(
        "--tool-call-parser",
        default="lfm2",
        help="the vLLM tool-call parser the card's nvsh snippet names (default: lfm2)",
    )
    args = parser.parse_args(argv)
    try:
        revision = build(
            merged=args.merged,
            base_snapshot=args.base_snapshot,
            repo=args.repo,
            run=args.run,
            results=args.results,
            data_summary=args.data_summary,
            out=args.out,
            licence_kind=args.licence_kind,
            tool_call_parser=args.tool_call_parser,
        )
    except ValueError as exc:
        parser.error(str(exc))
    print(f"bundle for {args.repo} ({args.run}, weights revision {revision}) in {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
