"""The committed README recordings still match the panel that is on disk.

``docs/demos/demo-<device>.cast`` is a scripted session (``scripts/
demo-record.py``) recorded on that device with the ``demo`` adapter. It is
regenerated by hand (docs/demos/README.md, "Re-recording"); nothing in CI
re-records it. These tests are the drift alarm: when the scenario, the
fixture's wording or the panel's key legend changes, the committed casts
fail here until someone re-records them.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from nvsh import panel
from nvsh.agent import demo

REPO_ROOT = Path(__file__).resolve().parent.parent
DEMOS = REPO_ROOT / "docs" / "demos"
DEVICES = ("spark", "thor", "orin")
#: The platform word each device's recording must name (the demo reply's
#: ``{platform}`` is the detected kind on that device).
PLATFORM_WORD = {"spark": "dgx-spark", "thor": "jetson", "orin": "jetson"}

_CONTROL = re.compile(r"\x1b\][^\x07]*\x07|\x1b\[[0-9;?]*[A-Za-z]")


def _plain(cast: Path) -> str:
    lines = cast.read_text(encoding="utf-8").splitlines()
    out = "".join(json.loads(line)[2] for line in lines[1:] if json.loads(line)[1] == "o")
    return _CONTROL.sub("", out)


@pytest.mark.parametrize("device", DEVICES)
def test_cast_and_svg_are_committed(device):
    assert (DEMOS / f"demo-{device}.cast").is_file()
    svg = DEMOS / f"demo-{device}.svg"
    assert svg.is_file()
    assert svg.read_bytes().lstrip().startswith(b"<svg")


@pytest.mark.parametrize("device", DEVICES)
def test_cast_shows_the_scenario_end_to_end(device):
    text = _plain(DEMOS / f"demo-{device}.cast")
    assert "./run-model.sh: Permission denied" in text
    assert "chmod +x ./run-model.sh" in text
    assert "model loaded, 42 tokens/s" in text  # the retry after the approved fix
    assert "(scripted demo reply)" in text


@pytest.mark.parametrize("device", DEVICES)
def test_cast_names_the_device_platform(device):
    text = _plain(DEMOS / f"demo-{device}.cast")
    assert f"Exit 126 on this {PLATFORM_WORD[device]} box" in text


@pytest.mark.parametrize("device", DEVICES)
def test_cast_carries_the_current_panel_legend(device):
    """A panel legend change means the recordings are stale."""
    text = _plain(DEMOS / f"demo-{device}.cast")
    assert panel.LEGEND in text


@pytest.mark.parametrize("device", DEVICES)
def test_cast_carries_the_current_fixture_wording(device):
    """A fixture edit means the recordings are stale."""
    data = json.loads(demo.FIXTURE_PATH.read_text(encoding="utf-8"))
    text = _plain(DEMOS / f"demo-{device}.cast")
    for event in data["events"]:
        if event.get("kind") != "text_delta":
            continue
        line = (
            event["text"]
            .replace(demo.SCRIPT_PLACEHOLDER, "./run-model.sh")
            .replace(demo.PLATFORM_PLACEHOLDER, PLATFORM_WORD[device])
            .strip()
        )
        assert line in text


@pytest.mark.parametrize("device", DEVICES)
def test_cast_is_scrubbed_of_hosts_and_lan_addresses(device):
    text = _plain(DEMOS / f"demo-{device}.cast")
    assert not re.search(r"\b\d{1,3}(?:\.\d{1,3}){3}\b", text), "an IPv4 leaked"
    assert "@" not in text.split("[Enter]")[0]  # no user@host prompt
    header = json.loads((DEMOS / f"demo-{device}.cast").read_text().splitlines()[0])
    assert header["timestamp"] == 0
