"""scripts/lfm-finetune/release_bundle.py (issue 39, t15): the upload folder's licence duties."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "lfm-finetune" / "release_bundle.py"

_LICENSE = "LFM Open License v1.0 \n\nTERMS AND CONDITIONS\n"
_RESULTS = """# Tier 2 measurement

intro

| Metric | model |
|---|---|
| Right operation and arguments proposed, per source | 25 of 32 |

## Background
"""


def _module():
    spec = importlib.util.spec_from_file_location("release_bundle", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _base(tmp_path: Path, template: str = "T", licence: str | None = _LICENSE) -> Path:
    snapshot = tmp_path / "hub" / "models--LiquidAI--LFM2.5-350M" / "snapshots" / ("a" * 40)
    snapshot.mkdir(parents=True)
    (snapshot / "chat_template.jinja").write_text(template)
    if licence is not None:
        (snapshot / "LICENSE").write_text(licence)
    return snapshot


def _merged(tmp_path: Path, template: str = "T") -> Path:
    merged = tmp_path / "merged"
    merged.mkdir()
    (merged / "chat_template.jinja").write_text(template)
    (merged / "model.safetensors").write_bytes(b"tuned")
    return merged


def _build(tmp_path: Path, **overrides):
    results = tmp_path / "r7-val.md"
    results.write_text(_RESULTS)
    if "merged" not in overrides:
        overrides["merged"] = _merged(tmp_path)
    if "base_snapshot" not in overrides:
        overrides["base_snapshot"] = _base(tmp_path)
    kwargs = dict(
        repo="jetson-ai-lab/lfm2.5-350m-nvsh-triage",
        run="r7",
        results=results,
        data_summary="945 examples from nvsh's train split.",
        out=tmp_path / "bundle",
    )
    kwargs.update(overrides)
    return _module().build(**kwargs)


def test_the_bundle_carries_weights_licence_notice_and_card(tmp_path) -> None:
    revision = _build(tmp_path)
    out = tmp_path / "bundle"
    assert len(revision) == 40
    assert (out / "model.safetensors").read_bytes() == b"tuned"
    assert (out / "LICENSE").read_text() == _LICENSE
    notice = (out / "NOTICE").read_text()
    assert "modified version of LiquidAI/LFM2.5-350M" in notice
    assert "a" * 40 in notice
    card = (out / "README.md").read_text()
    assert card.startswith("---\n")
    assert "license_name: lfm1.0" in card
    assert "base_model: LiquidAI/LFM2.5-350M" in card
    assert "10,000,000" in card
    assert "every user" in card
    assert "| Right operation and arguments proposed, per source | 25 of 32 |" in card
    assert "## Background" not in card
    assert "Generated by" in card
    assert "Reviewed by" in card
    assert "945 examples" in card


def test_a_changed_chat_template_is_refused(tmp_path) -> None:
    merged = _merged(tmp_path, template="other")
    with pytest.raises(ValueError, match="chat template"):
        _build(tmp_path, merged=merged)


def test_a_base_without_the_lfm_licence_is_refused(tmp_path) -> None:
    base_snapshot = _base(tmp_path, licence=None)
    with pytest.raises(ValueError, match="LICENSE"):
        _build(tmp_path, base_snapshot=base_snapshot)


def test_a_different_licence_is_refused(tmp_path) -> None:
    base_snapshot = _base(tmp_path, licence="Apache License\n")
    with pytest.raises(ValueError, match="LFM Open License"):
        _build(tmp_path, base_snapshot=base_snapshot)


def test_an_empty_data_summary_is_refused(tmp_path) -> None:
    with pytest.raises(ValueError, match="data-summary"):
        _build(tmp_path, data_summary="  ")


def test_a_non_empty_output_folder_is_refused(tmp_path) -> None:
    out = tmp_path / "bundle"
    out.mkdir()
    (out / "old").write_text("x")
    with pytest.raises(ValueError, match="not empty"):
        _build(tmp_path, out=out)


def test_results_without_a_table_are_refused(tmp_path) -> None:
    results = tmp_path / "empty.md"
    results.write_text("# nothing\n")
    with pytest.raises(ValueError, match="no metric table"):
        _build(tmp_path, results=results)
